### ISSUE TITLE
Just fetch a query instead of the whole list

### ISSUE THREAD

**Issue by Jakobud** [dafrancis/Sublime-Text--cdnjs#36]
Awesome and useful plugin but the biggest issue with it is that fetching the entire list of CDNJS items takes WAAAAAAY too long. And this list is only going to be bigger and bigger as time goes on.

Why don't you change the plugin to instead, before fetching anything, ask for a search query, and then only fetch a list of items based off that query?

For example, you choose CDNJS: Import Script then the plugin asked you to search for a plugin, then the user types something like "bootstrap" or "jquery". Then the plugin fetches a list of CDNJS scripts based off of that search.

This would be much faster and make the whole thing more usable.

Also it seems to have to fetch the entire CDNJS list everytime you use the plugin. Why doesn't it cache anything?

**Comment by dafrancis** [comment]
There's already "CDNS: search".which does what you ask.

The "caching" isn't a problem (as in saving the list from the CDNJS isn't a problem). The problem is that the list is "huge" (to get what I mean, try opening `package_list.cdncache` in Sublime. It takes a while). I haven't found a neat way to load that huge json file quickly without having to rewrite this whole plugin I'm afraid.
