### ISSUE TITLE
package_list.cdncache file in users home

### ISSUE THREAD

**Issue by CodeBrauer** [dafrancis/Sublime-Text--cdnjs#37]
This file is just saved in the users home directory. (`sublime.packages_path() `)
Please move it to the sublime package directory or somewhere else but hidden for the normal user.

**Comment by dafrancis** [comment]
~~A bit of history on this:~~

~~Long time ago (https://github.com/dafrancis/Sublime-Text--cdnjs/issues/25) people were getting issues where the package_list.cdncache wasn't being found in the packages list. My fix (although hacky) was to get the cache from the user's home directory.~~

~~It's not the most ideal situation here, but at the time I was getting problems from people from different operating systems and different versions of sublime (making 6 versions altogether). Each one had a weird way on how it did things, so in order to make sure that it was consistent on every version I forced it to go in the home directory.~~

~~I don't really want to fix this, not because of laziness, but because I can't guarantee that I can get this working an all operating systems. I only have a windows at the moment so I don't really want to risk changing this for windows versions of sublime text and have it break completely for mac and linux (despite the fact that this originally happened because of an issue with Sublime Text 2 on windows).~~

# no

**Comment by MaxPleaner** [comment]
I was cleaning out my home directory and found this 100MB file. 

Not sure what it was, I searched on Google and this issue was the first result.

If it is going to be saved in the users home directory, it'd be better if it was named something a little clearer such as `cdnjs_sublime_package_list.cdncache`.
