### ISSUE TITLE
List of files not displaying

### ISSUE THREAD

**Issue by rgbjoy** [dafrancis/Sublime-Text--cdnjs#38]
Getting error in console on Sublime Text 3:

```
TypeError: on_change() takes 1 positional argument but 2 were given\n
TypeError: on_change() takes 1 positional argument but 2 were given
TypeError: on_change() takes 1 positional argument but 2 were given
TypeError: on_change() takes 1 positional argument but 2 were given
TypeError: on_change() takes 1 positional argument but 2 were given
TypeError: on_change() takes 1 positional argument but 2 were given
TypeError: on_change() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "picker in /Users/_USER_/Library/Application Support/Sublime Text 3/Installed Packages/cdnjs.sublime-package", line 78, in show_quickpanel
  File "picker in /Users/_USER_/Library/Application Support/Sublime Text 3/Installed Packages/cdnjs.sublime-package", line 75, in get_list
  File "picker in /Users/_USER_/Library/Application Support/Sublime Text 3/Installed Packages/cdnjs.sublime-package", line 75, in <listcomp>
AttributeError: 'str' object has no attribute 'get'
```

**Comment by dafrancis** [comment]
This issue was happening due to packages.json on cdnjs changing. The files are now listed as an array of strings rather than an array of objects. Changes have been made in the plugin to reflect this.

**Comment by rgbjoy** [comment]
Is it me or is this still happening? I removed and reinstalled. Still getting "on_change() takes 1 positional argument but 2 were given"

**Comment by dafrancis** [comment]
For a moment I was confused as to what you meant by "still happening". The functionality that was broken seemed to be working for me.

That was until I realised you weren't talking about the dropdown throwing errors (which was fixed) and talking about an unrelated message. This has been fixed, but it would be helpful next time if you actually write the issues down in the ticket because your original message made it seem that you were just reporting about the dropdown not displaying.

Separate tickets for each issue and a helpful description that isn't "not working" (for example "Warnings are creating noise in the console") doesn't hurt either.

Thanks
